#include "globals.h"

BalanceCarInfo g_BALANCE_CAR_INFO;

RRD_DEVICE_MOTOR* g_MOTOR_DEVICE_LEFT;
RRD_DEVICE_MOTOR* g_MOTOR_DEVICE_RIGHT;

RRD_DEVICE_TB6612FNG* g_TB6612FNG_DEVICE_LEFT;
RRD_DEVICE_TB6612FNG* g_TB6612FNG_DEVICE_RIGHT;

RRD_DRIVER_ENCODER* g_ENCODER_DEVICE_LEFT;
RRD_DRIVER_ENCODER* g_ENCODER_DEVICE_RIGHT;









